---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--args=--sort-by=required']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  # Talisman pre-commit hook declaration is broken; pre-commit cannot build from
  # source. Use the talisman binary installed in container.
  - repo: https://gist.github.com/42f82959d980813c44feeab30a7661f9
    rev: HEAD
    hooks:
      - id: talisman-commit
