---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--args=--sort-by=required']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  # Talisman pre-commit hook declaration is broken; pre-commit cannot build from
  # source. Use the talisman binary installed in container/user environment.
  - repo: local
    hooks:
      - id: local-talisman
        name: talisman
        entry: talisman --githook pre-commit
        stages:
          - commit
        pass_filenames: false
        types:
          - text
        language: system
